spring:
  mail:
    host: smtp.163.com
    port: 25
    username: autumndeforest@163.com
    password: SVXMFYNUNRFRKXHE
    default-encoding: UTF-8
    protocol: smtp

  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zhanghui
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  session:
    store-type: redis
logging:
  file:
    path: D:/WorkSpace/mall-modified/mall-admin/src/main/java/cn/zhang/mallmodified/log
